// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"; // Keep this if you use custom .env paths
import { defineConfig, env } from "prisma/config"; // Added 'env' helper

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Using the helper for better CLI error reporting
    url: env("DATABASE_URL"),
  },
});
